---
# ba0fde3d-bee7-4307-b97b-17d0d20aff50
name: Build image
on:
  pull_request:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG: ${{ steps.set.outputs.LATEST_TAG }}
      REGISTRY: ${{ steps.set.outputs.REGISTRY }}
      REGISTRY_USER: ${{ steps.set.outputs.REGISTRY_USER }}
      PLATFORMS: ${{ steps.set.outputs.PLATFORMS }}
      IMAGE_PATH: ${{ steps.set.outputs.IMAGE_PATH }}
      IMAGE_NAME: ${{ steps.set.outputs.IMAGE_NAME }}
      IMAGE_REF: ${{ steps.set.outputs.IMAGE_REF }}
      IMAGE_TYPES: ${{ steps.set.outputs.IMAGE_TYPES }}
      IS_SIGNED: ${{ steps.set.outputs.IS_SIGNED }}
    steps:
      - name: Checkout github actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - name: Set environment variables
        uses: ./.github/actions/config
        id: set
        with:
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

  build-image:
    name: Build image
    uses: eseiker/atomic-ci/.github/workflows/build-image.yml@7dff8c8b24ba24b0c6423eb97adf16a98f19294b
    needs: [set-env]
    with:
      INTERNAL_ACTIONS_REPO: eseiker/atomic-ci
      INTERNAL_ACTIONS_REF: 7dff8c8b24ba24b0c6423eb97adf16a98f19294b
      image-description: "AlmaLinux Asahi bootc image"
      containerfile: Dockerfile
      image-name: "${{ needs.set-env.outputs.IMAGE_NAME }}"
      previous-image: "${{ needs.set-env.outputs.IMAGE_REF }}:latest"
      upstream-public-key: bootc-images.pub
      platforms: ${{ needs.set-env.outputs.PLATFORMS }}
      skip-maximize-build-space: true
      image-path: ${{ needs.set-env.outputs.IMAGE_PATH }}
      changelog-snippet: |
        Major Components:
          - Kernel: <relver:kernel-16k>
          - Systemd: <relver:systemd>
          - Glibc: <relver:glibc>
          - Bootc: <relver:bootc>
      REGISTRY: ${{ needs.set-env.outputs.REGISTRY }}
      REGISTRY_USER: ${{ needs.set-env.outputs.REGISTRY_USER }}
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    permissions:
      contents: read
      packages: write
      id-token: write
  
  image-ref-digest:
    needs: [build-image]
    runs-on: ubuntu-24.04-arm
    outputs:
      IMAGE_REF_DIGEST: ${{ steps.set.outputs.IMAGE_REF_DIGEST }}
    steps:
      - id: set
        run: echo "IMAGE_REF_DIGEST=${{ needs.build-image.outputs.image-ref }}@${{ needs.build-image.outputs.digest }}" >> $GITHUB_OUTPUT

  test-image:
    name: Test image
    runs-on: ubuntu-24.04-arm
    needs: [set-env, image-ref-digest]
    permissions:
      packages: read
    steps:
      - name: Login to Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | podman login -u ${{ needs.set-env.outputs.REGISTRY_USER }} --password-stdin ${{ needs.set-env.outputs.REGISTRY }}
      - name: Test container
        run: |
          # Create a short script to test the image using heredoc
          cat << 'EOF' > /tmp/test.sh
          set -ex

          cat /etc/os-release
          bootc -V
          EOF

          podman run --rm \
            -v /tmp/test.sh:/tmp/test.sh \
            ${{ needs.image-ref-digest.outputs.IMAGE_REF_DIGEST }} \
            /bin/bash /tmp/test.sh

  build-installer-image:
    name: Build installer image
    uses: eseiker/atomic-ci/.github/workflows/build-image.yml@7dff8c8b24ba24b0c6423eb97adf16a98f19294b
    needs: [set-env, image-ref-digest, test-image]
    if: ${{ contains(needs.set-env.outputs.IMAGE_TYPES, 'bootc-installer') }}
    with:
      INTERNAL_ACTIONS_REPO: eseiker/atomic-ci
      INTERNAL_ACTIONS_REF: 7dff8c8b24ba24b0c6423eb97adf16a98f19294b
      image-description: "AlmaLinux Asahi bootc installer image"
      containerfile: Dockerfile
      stage: installer
      extra-args: --build-arg "BASE_IMAGE=${{ needs.image-ref-digest.outputs.IMAGE_REF_DIGEST }}"
      image-name: "${{ needs.set-env.outputs.IMAGE_NAME }}-installer"
      previous-image: "${{ needs.set-env.outputs.IMAGE_REF }}-installer:latest"
      upstream-public-key: bootc-images.pub
      platforms: ${{ needs.set-env.outputs.PLATFORMS }}
      skip-maximize-build-space: true
      image-path: ${{ needs.set-env.outputs.IMAGE_PATH }}
      changelog-snippet: "BASE_IMAGE=${{ needs.image-ref-digest.outputs.IMAGE_REF_DIGEST }}"
      REGISTRY: ${{ needs.set-env.outputs.REGISTRY }}
      REGISTRY_USER: ${{ needs.set-env.outputs.REGISTRY_USER }}
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    permissions:
      contents: read
      packages: write
      id-token: write

  prepare-build-bootable-artifacts-args:
    name: Prepare build-bootable-artifacts arguments
    needs: [set-env, build-image, image-ref-digest, test-image, build-installer-image]
    if: ${{
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
          && always() && needs.test-image.result == 'success'
        }}
    runs-on: ubuntu-24.04-arm
    outputs:
      IMAGE: ${{ steps.set.outputs.IMAGE }}
      ADDITIONAL_ARGS: ${{ steps.set.outputs.ADDITIONAL_ARGS }}
    steps:
      - id: set
        run: |
          IS_BOOTC_INSTALLER=$([[ "${{ needs.set-env.outputs.IMAGE_TYPES }}" == *"bootc-installer"* ]] && echo "true" || echo "false")

          if [[ $IS_BOOTC_INSTALLER == "true" ]]; then
            IMAGE="${{ needs.build-installer-image.outputs.image-ref }}@${{ needs.build-installer-image.outputs.digest }}"
            echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT
            # echo "ADDITIONAL_ARGS=--installer-payload-ref=${{ needs.image-ref-digest.outputs.IMAGE_REF_DIGEST }}" >> $GITHUB_OUTPUT
            # temporary workaround
            echo "ADDITIONAL_ARGS=--installer-payload-ref=${IMAGE}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE=${{ needs.image-ref-digest.outputs.IMAGE_REF_DIGEST }}" >> $GITHUB_OUTPUT
            echo "ADDITIONAL_ARGS=--rootfs=btrfs" >> $GITHUB_OUTPUT
          fi

  build-bootable-artifacts:
    name: Build Bootable Artifacts
    needs: [set-env, image-ref-digest, prepare-build-bootable-artifacts-args]
    if: ${{ always() && needs.prepare-build-bootable-artifacts-args.result == 'success' }}
    uses: eseiker/atomic-ci/.github/workflows/build-bootable-artifacts.yml@7dff8c8b24ba24b0c6423eb97adf16a98f19294b
    with:
      INTERNAL_ACTIONS_REPO: eseiker/atomic-ci
      INTERNAL_ACTIONS_REF: 7dff8c8b24ba24b0c6423eb97adf16a98f19294b
      image-name: "${{ needs.set-env.outputs.IMAGE_NAME }}"
      image: "${{ needs.prepare-build-bootable-artifacts-args.outputs.IMAGE }}"
      update_origin_ref: "${{ needs.image-ref-digest.outputs.IMAGE_REF_DIGEST }}"
      update_is_signed: ${{ needs.set-env.outputs.IS_SIGNED == 'true' }}
      config-file: ./config.toml
      platforms: ${{ needs.set-env.outputs.PLATFORMS }}
      image-types: ${{ needs.set-env.outputs.IMAGE_TYPES }}
      additional-args: ${{ needs.prepare-build-bootable-artifacts-args.outputs.ADDITIONAL_ARGS }}
      REGISTRY: ${{ needs.set-env.outputs.REGISTRY }}
      REGISTRY_USER: ${{ needs.set-env.outputs.REGISTRY_USER }}
      upload-to-cloudflare: false
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  promote-image:
    name: Promote image
    needs: [set-env, build-image, test-image, build-bootable-artifacts]
    if: ${{ always() && needs.build-bootable-artifacts.result == 'success' }}
    uses: eseiker/atomic-ci/.github/workflows/retag-image.yml@95206d08ea4b085ccadd7f281e9eecf6e9fe2af7
    with:
      image: ${{ needs.build-image.outputs.image-ref }}
      digest: ${{ needs.build-image.outputs.digest }}
      tag: |
        ${{ needs.set-env.outputs.LATEST_TAG }}
        ${{ needs.build-image.outputs.major-version }}
        ${{ needs.build-image.outputs.redhat-version-id }}
        ${{ needs.build-image.outputs.version }}
      REGISTRY: ${{ needs.set-env.outputs.REGISTRY }}
      REGISTRY_USER: ${{ needs.set-env.outputs.REGISTRY_USER }}
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write

  create-release:
    name: Create Release
    needs: [set-env, build-image, promote-image]
    if: ${{ always() && needs.promote-image.result == 'success' }}
    uses: eseiker/atomic-ci/.github/workflows/create-release.yml@7dff8c8b24ba24b0c6423eb97adf16a98f19294b
    with:
      image-name: "${{ needs.set-env.outputs.IMAGE_NAME }}"
      version: ${{ needs.build-image.outputs.version }}
      pretty-version: ${{ needs.build-image.outputs.redhat-version-id }}
      latest-image-ref: "${{ needs.build-image.outputs.image-ref }}:${{ needs.set-env.outputs.LATEST_TAG }}"
    permissions:
      contents: write
